language: scala
sudo: false
jdk:
- oraclejdk8
script:
- sbt clean test riffRaffUpload
cache:
  directories:
  - $HOME/.sbt/0.13
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/cache
  - $HOME/.sbt/launchers
  - $HOME/.ivy2
before_cache:
- du -h -d 1 $HOME/.ivy2/
- du -h -d 2 $HOME/.sbt/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

env:
  global:
    - secure: "Fn1vYEGNKlzIQFo/AUTvHan+3lyiNrXo3nClDJgBu1ZCVCM7wWp7ocbZbxEt4IDKtLikchDie1ff6ub50cmxPfgiI1z/dvDvBKHicP8ku8ppdI7VLgTy7xcU/wYoy9Kn7q81zElXS55hlQ9ToKrZbXdUgXRCOU8BCKGVOdsHL+qQZ8yFAUnWh+7vdl1cBefuAf3zO5JPnSNB1b71x/61D3HNhKqOXczgG7oK6WcYGVJwcbASD10bTEeLIwIXk8jrWcn6Su8SPV1+jqGVwwdVITsO/WtaijimOZzgJ5FeZuBe7MnfggwNSheHlhKdrEQ1H+kPK+3i4M9q/wZ/6ZRKOafMCsVby1OCOqBGajQBv+KSJzmkur3Wvce9OKNfyNSHG21ctwa5W9p8O2FV1uqvRfD95CpTHrWTZkjM+ysMn1y9oGLOdHTWvvkX3VIP/kcYmRy+Ovr4aCviMrFYR8JorWGkG3YDJGNPG/XjhJdxhEN7AyvB3UyaM2KNNQrGa91PFfX8S5+m5NzqZ6y2pBWi0zcxuNKbw7jLbe7CKjBrpW/5gzAV5JzUUuQqoNHc7iz8UZfUn3v21OSDdeRjUobASiQ8X6W5lw5ZbCJ8nFUMjoIL+f7zksS0c0Nn9HU6SgfJDMEI8iPo8faDfC45xCMwnL8vI8tLhuDjJ8TnsIee11Q="
    - secure: "e/Swl1duZjZqb97a69A8QQr2kn/xv+XugO81wc3pbX62CduU3cucRfDO/Q28cL3sbBe/scIwY/WdLUgg6uQoLgw4qQLbVAzln9nAXzG6DJ9/Ac1r5iWXCuKuLhjDhefgrZbGy7+vxjhrg9ruE62AomjU4AcmfdWDy7lo+XxqGgRKHX4sBl4giTQYftaqayQSlQm5HWkmO0YE678+KTYRGdEyLYE8NhD+DhWnlkBgDa7cIXTuflHxdCezh8fgeWxJvRdJtMramQtrwnalKXVcbhI4U81lldbRTLppNoM0h4JbsNjt6Pvyx5MIHKyFagT7MpIU5bvDXrYljImyLxKvlh5O9+k7PubHJ5/eRRKcrtbTb6r52kGcX/TTKf5hyN3JquZE+ph4P1gSGnHe/0OW14rjbSl87wMF8ajEk54TbUNHwMhZWJgVUBwwQjNhrzUD59sT12aBXncKH1AGORK2SPBHLBa4RFf+B3b0EGZFjQSXa4LcPckufeQt23bC+K43svWKZpt0YmqnoDdPAHVJ/7QCGKZjzhiCQ3D5YjxIy+N+wB/JA3tNBQAYxUku4hX3XDir/AucmJIieaEgeQJRQHs4Ph/oYZeYasLnrEnuthBR5CaMSrWwVUagV+UC3iXAODssXYytTDd1ObyXshqN+VDDSsns0kFAe8c3sBIWBbo="