AWSTemplateFormatVersion: '2010-09-09'
Description: 'Frontend Notifications Infrastructure'

Parameters:
  GCMSubscriptionsTableName:
    Description: The table name of the GCM Subscriptions Table
    Type: String
  GCMWorkerQueueName:
    Description: The name of the GCM work queue
    Type: String
  TopicMessageQueueName:
    Description: The name of the topic message queue
    Type: String

Resources:
  GCMWorkerQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: {Ref: GCMWorkerQueueName}

  TopicMessageQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: {Ref: TopicMessageQueueName}

  GCMSubscriptionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: {Ref: GCMSubscriptionsTableName}
      KeySchema:
        - {AttributeName: notificationTopicId, KeyType: HASH}
        - {AttributeName: gcmBrowserId, KeyType: RANGE}
      AttributeDefinitions:
        - {AttributeName: notificationTopicId, AttributeType: S}
        - {AttributeName: gcmBrowserId, AttributeType: S}
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10

